name: setup-wally
description: GitHub action to set Wally and Git credentials, and install packages.
branding:
  icon: arrow-down-circle
  color: blue

inputs:
  install-aftman:
    description: "Should Aftman be installed"
    required: false
    default: false
    type: boolean
  install-foreman:
    description: "Should Foreman be installed"
    required: false
    default: false
    deprecationMessage: "Foreman has been deprecated in favour of Aftman"
    type: boolean
  install-packages:
    description: "Should `wally install` be run"
    required: false
    default: true
    type: boolean
  token:
    description: "Token for publishing packages or accessing private registries"
    required: false
    type: string
  registry:
    description: "The registry endpoint to set an auth token for"
    required: false
    default: "https://api.wally.run/"
    type: string
  git-credentials:
    description: "Credentials to access private registry repositories"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Aftman
      if: ${{ inputs.install-aftman }}
      uses: ok-nick/setup-aftman@v0.3.0

    - name: Install Foreman
      if: ${{ inputs.install-foreman }}
      uses: Roblox/setup-foreman@v1
      with:
        token: ${{ github.token }}
      
    - name: Set git credentials
      if: ${{ inputs.git-credentials }}
      run: |
        git config --global credential.helper store
        echo "${{ inputs.git-credentials }}" > $HOME/.git-credentials
      shell: bash
        
    - name: Set auth token
      if: ${{ inputs.token }}
      run: |
        mkdir -p $HOME/.wally
        cat >> $HOME/.wally/auth.toml << EOF
        [tokens]
        "${{ inputs.registry }}" = "${{ inputs.token }}"
        EOF
      shell: bash
        
    - name: Install packages
      if: ${{ inputs.install-packages }}
      run: wally install
      shell: bash   
