name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Test
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.REGISTRY_API_KEY }}
          registry: "https://github.com/Mindblast-Games/wally-index"
          git-credentials: ${{ secrets.REGISTRY_GIT_CREDENTIALS }}
          install-aftman: true
